# Linear filter parameters
left_alpha : 0.9 # range = [0,1], more means trust the filtered data more
right_alpha : 0.9 # range = [0,1], more means trust the filtered data more
alpha : 0.95 # range = [0,1], more means trust the filtered data more

# grid configuration
object:
  name: "hand" # the published pose and filtered pose will be preappended with this value

hand_side : "Right" # this can be "Right" or "Left"

left_confidence_threshold : 0.5
right_confidence_threshold : 0.5

hand_to_object_offsets: #wrt world
  x: 0.0
  y: -0.05
  z: 0.0

# hand false positive elements
# this is wrt world frame
bounding_box:
  x_min: -0.5
  x_max: 0.5
  y_min: -0.07
  y_max: 0.3
  z_min: -0.5
  z_max: 1.0

# Camera topics
left_color_image_topic : "/left_camera/rgb/image_raw"
left_depth_image_topic : "/left_camera/depth_to_rgb/image_raw" # of aligned depth to rgb
left_camera_info_topic : "/left_camera/rgb/camera_info"

right_color_image_topic : "/right_camera/rgb/image_raw"
right_depth_image_topic : "/right_camera/depth_to_rgb/image_raw" # of aligned depth to rgb
right_camera_info_topic : "/right_camera/rgb/camera_info"