# Linear filter parameters
left_alpha : 0.25 # range = [0,1], more means trust the filtered data more
right_alpha : 0.25 # range = [0,1], more means trust the filtered data more

# grid configuration
object:
  name: "hand" # the published pose and filtered pose will be preappended with this value

hand_side : "Right" # this can be "Right" or "Left"

left_confidence_threshold : 0.5
right_confidence_threshold : 0.5

# hand false positive elements
bounding_box:
  x_min: 0.0
  x_max: 2.0
  y_min: 0.0
  y_max: 2.0
  z_min: 0.0
  z_max: 2.0

# Camera topics
left_color_image_topic : "/left_camera/rgb/image_raw"
left_depth_image_topic : "/left_camera/depth_to_rgb/image_raw" # of aligned depth to rgb
left_camera_info_topic : "/left_camera/rgb/camera_info"

right_color_image_topic : "/right_camera/rgb/image_raw"
right_depth_image_topic : "/right_camera/depth_to_rgb/image_raw" # of aligned depth to rgb
right_camera_info_topic : "/right_camera/rgb/camera_info"