default_position :
  position: 
    x: 0.4900047348582851
    y: -0.3327029075470745
    z: 0.07962184310047295
  orientation: 
    x: 0.5170939822399835
    y: 0.47693358155780274
    z: 0.4805113539030173
    w: 0.5236955328088371

use_default_position : True

preplace_transformation :
  position:
    x: 0.0
    y: 0.0
    z: 0.05
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

max_linear_acceleration : 10 #m/s^2
max_linear_velocity : 1 #m/s
max_angular_acceleration : 17.45 # rad/s^2
max_angular_velocity : 3.14 # rad/s

pose_setpoint_frequency_cuttoff : 20 #hz
cmd_publish_frequency : 100 #hz

linear_stop_threshold : 0.007 # having a higher threshold means faster stop because of how PID works
angular_stop_threshold : 0.01

gains :
  linear : 
    p : 750
    i : 0
    d : 0
    k : 0.01
  angular : 
    p : 150
    i : 0
    d : 0
    k : 0.01


pre_grasp_transform : # transformation from grasp -> pregrasp
  position :
    x : 0.0
    y : 0.0
    z : -0.1
  orientation :
    w : 1 
    x : 0
    y : 0
    z : 0