default_position :
  position:
    x: 0.719485937580114
    y: 0.11426366098174431
    z: 0.9601198065416131
  orientation:
    x: 0.5158333052982221
    y: 0.49760767471961076
    z: 0.4910325096569348
    w: 0.4951663131365716

use_default_position : True

go_back : 0.15 #m

alpha : 0.6

input_stream_timeout : 0.2 #s

preplace_transformation :
  position:
    x: 0.0
    y: 0.0
    z: 0.05
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

max_linear_acceleration : 10 #m/s^2
max_linear_velocity : 1 #m/s
max_angular_acceleration : 17.45 # rad/s^2
max_angular_velocity : 3.14 # rad/s

pose_setpoint_frequency_cuttoff : 20 #hz
cmd_publish_frequency : 100 #hz

linear_stop_threshold : 0.007 # having a higher threshold means faster stop because of how PID works
angular_stop_threshold : 0.01

gains :
  linear : 
    p : 1000
    i : 0
    d : 0
    k : 0.01
  angular : 
    p : 300
    i : 0
    d : 0
    k : 0.01


pre_grasp_transform : # transformation from grasp -> pregrasp
  position :
    x : 0.0
    y : 0.0
    z : -0.1
  orientation :
    w : 1 
    x : 0
    y : 0
    z : 0