default_position :
  position: 
    x: 0.7061368880686721
    y: -0.2911768963254483
    z: 0.013040072487731806
  orientation: 
    x: 0.4925710193689137
    y: 0.5204868841056627
    z: 0.48526857929807593
    w: 0.5009806386457212

use_default_position : True

setpoint_interpolation_duration : 1.0 # how fast the setpoint moves from current to goal, lower means faster

go_back : 0.15 #m

alpha : 0.15

input_stream_timeout : 0.2 #s

preplace_transformation :
  position:
    x: 0.0
    y: 0.0
    z: 0.05
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0

max_linear_acceleration : 10 #m/s^2
max_linear_velocity : 1 #m/s
max_angular_acceleration : 17.45 # rad/s^2
max_angular_velocity : 3.14 # rad/s

pose_setpoint_frequency_cuttoff : 20 #hz
cmd_publish_frequency : 100 #hz

linear_stop_threshold : 0.01 # having a higher threshold means faster stop because of how PID works
angular_stop_threshold : 0.01

gains :
  linear : 
    p : 300
    i : 75
    d : 150
    k : 0.01
  angular : 
    p : 100
    i : 0
    d : 0
    k : 0.01


pre_grasp_transform : # transformation from grasp -> pregrasp
  position :
    x : 0.0
    y : 0.0
    z : -0.1
  orientation :
    w : 1 
    x : 0
    y : 0
    z : 0