max_linear_acceleration : 10 #m/s^2
max_linear_velocity : 1 #m/s
max_angular_acceleration : 17.45 # rad/s^2
max_angular_velocity : 3.14 # rad/s

input_stream_timeout : 0.2 #s
cmd_publish_frequency : 100 #hz

linear_stop_threshold : 0.02 # having a higher threshold means faster stop because of how PID works
angular_stop_threshold : 0.02

# vanilla pidk and filtered_grasp_pose axes weighted K for trajectory based pid control
gains :
  linear : 
    p : 150
    i : 0
    d : 0
    X : 
      k : 0.1
    Y :
      k : 0.1
    Z : 
      k : 0.05
    
  angular : 
    p : 1000
    i : 0
    d : 0
    k : 0.01