max_linear_acceleration : 10 #m/s^2
max_linear_velocity : 1 #m/s
max_angular_acceleration : 17.45 # rad/s^2
max_angular_velocity : 3.14 # rad/s

pose_setpoint_frequency_cuttoff : 2 #hz
cmd_publish_frequency : 1000 #hz

gains :
  linear : 
    p : 500
    i : 0
    d : 0
    k : 0.01
  angular : 
    p : 2
    i : 0
    d : 0
    k : 1

pre_grasp_transform : # transformation from grasp -> pregrasp
  position :
    x : -0.1
    y : 0.0
    z : 0.0
  orientation :
    w : 1 
    x : 0
    y : 0
    z : 0